### ISSUE TITLE
klipper-moonraker container doesn't work (v2)

### ISSUE THREAD

**Issue by Andoramb** [dimalo/klipper-web-control-docker#24]
Hey,
I've updated the containers, rebuilt the images based on both develop an main branches, but now the klipper-moonraker container is not starting.
Tried to look at the logs, this is what I've found:
```
klipper-moonraker | [shell_command.py:_create_subprocess()] - shell_command: Command (systemctl list-units --all --type=service --plain --no-legend) failed
klipper-moonraker | Traceback (most recent call last):
klipper-moonraker |   File "/home/klippy/moonraker/moonraker/components/shell_command.py", line 256, in _create_subprocess
klipper-moonraker |     transport, protocol = await loop.subprocess_exec(
klipper-moonraker |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1652, in subprocess_exec
klipper-moonraker |     transport = await self._make_subprocess_transport(
klipper-moonraker |   File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
klipper-moonraker |     transp = _UnixSubprocessTransport(self, protocol, args, shell,
klipper-moonraker |   File "/usr/local/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
klipper-moonraker |     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
klipper-moonraker |   File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 799, in _start
klipper-moonraker |     self._proc = subprocess.Popen(
klipper-moonraker |   File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
klipper-moonraker |     self._execute_child(args, executable, preexec_fn, close_fds,
klipper-moonraker |   File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
klipper-moonraker |     raise child_exception_type(errno_num, err_msg, err_filename)
klipper-moonraker | FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'
```

And another one says:  
```
2021-12-04 17:42:56,272 INFO success: klipper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-04 17:42:56,273 WARN received SIGTERM indicating exit request
2021-12-04 17:42:56,273 INFO waiting for dependentstartup, klipper to die
2021-12-04 17:42:57,275 - supervisord_dependent_startup - [INFO   ] 
2021-12-04 17:42:57,275 - supervisord_dependent_startup - [INFO   ] New event: Service klipper went from STARTING to RUNNING
2021-12-04 17:42:57,278 - supervisord_dependent_startup - [ERROR  ] Error occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 910, in run
    main()
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 904, in main
    event_listener.run_and_listen()
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 829, in run_and_listen
    self.listen()
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 822, in listen
    for l in self._listen():
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 817, in _listen
    event_parsed = self.handle_event(headers, payload)
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 757, in handle_event
    self.services_handler.update_proc_info()
  File "/usr/local/lib/python3.10/site-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 472, in update_proc_info
    info = self.rpc.supervisor.getAllProcessInfo()
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1458, in __request
    response = self.__transport.request(
  File "/usr/local/lib/python3.10/site-packages/supervisor/xmlrpc.py", line 554, in request
    return u.close()
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 6: 'SHUTDOWN_STATE'>
2021-12-04 17:42:57,282 INFO stopped: klipper (terminated by SIGTERM)
2021-12-04 17:42:57,288 INFO stopped: dependentstartup (terminated by SIGTERM)
```

Do you have any ideas what could it be?
Does someone else has this?
(by the way, the [pull request](https://github.com/dimalo/klipper-web-control-docker/pull/23)  for the macros should be fine)

**Comment by s0nify** [comment]
Try with python 3.9

**Comment by Andoramb** [comment]
Did a full rebuild and it worked on the 3rd attempt.
It was probably my steps/config then 👍 
Thanks! :)

**Comment by Andoramb** [comment]
Strange, upon restart I get the same errors and the container keeps restarting

**Comment by DrFatalis** [comment]
Same here, klipper container do not start correctly. Once all is started Mainsail nor Fluidd can find moonraker. I cannot make it work. 

[_klipper_logs.txt](https://github.com/dimalo/klipper-web-control-docker/files/7844146/_klipper_logs.txt)

**Comment by Andoramb** [comment]
@DrFatalis try to manually update with _git pull_
Or restart the whole process from scratch?

**Comment by DrFatalis** [comment]
@Andoramb image was pulled freshly this morning. I also tried to docker-compose build... Just in case and still the same. All container start but klipper is not accessible, even if I can ping the container from mainsail for example.

**Comment by Andoramb** [comment]
I don't have this error.
But I've observed that it can be problematic to _git pull_ if you edit specific lines in [client_macros.cfg](https://github.com/dimalo/klipper-web-control-docker/blob/b25e8474f02ddee974ade66175433016523327e6/config/client_macros.cfg#L68).
For ex. if you want to set different X params for your pause location.

**Comment by DrFatalis** [comment]
@Andoramb I updated my docker-compose.yml with the device below. I now have an error saying that i may running an old version of klipper which may be true 

 ```
devices:`
      #- /dev/ttyKlipperEnder:/dev/ttyUSB0
      - /dev/ttyKlipperEnder:/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00
```


![image](https://user-images.githubusercontent.com/5773055/149142952-0c237e6b-42e1-4eec-9795-6dfe5e2d8e0d.png)

**Comment by Andoramb** [comment]
I've compiled a klipper fw separately on a pi. It is one of the prerequisites of the repo :)
In theory it should be possible to flash the fw from this docker image. but that would be a different topic

**Comment by DrFatalis** [comment]
> @Andoramb I updated my docker-compose.yml with the device below. I now have an error saying that i may running an old version of klipper which may be true instead of the old issue (printer not ready --> aka cannot connect to the printer)
> 
> Any way to compile a new klipper firmware from your image ?
> 
> ```
> devices:
>      #- /dev/ttyKlipperEnder:/dev/ttyUSB0
>      - /dev/ttyKlipperEnder:/dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00
> ```
> 
> ![image](https://user-images.githubusercontent.com/5773055/149142952-0c237e6b-42e1-4eec-9795-6dfe5e2d8e0d.png)

docker exec -it klipper /bin/bash
apt update
apt install make
cd /home/klippy/klipper
make menuconfig 
make OR make flash (based on the motherboard) then move the firmware to a mounted volume to get it out of the container i assume

**Comment by Andoramb** [comment]
Stay inside the container and flash the image from there accoring to the [official docs](https://www.klipper3d.org/Installation.html#building-and-flashing-the-micro-controller)

**Comment by DrFatalis** [comment]
> Stay inside the container and flash the image from there accoring to the [official docs](https://www.klipper3d.org/Installation.html#building-and-flashing-the-micro-controller)

I had to export klipper.bin outside of the container as I need to flash manually my skr mini v2.0.

It is now working okay with the firmware updated from 0.9 to 0.10. However I suppose that the device ttyUSB0 may need to be updated to /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00 (according to what is expected in the doc)

**Comment by dimalo** [comment]
hey fellows sorry for being late to the discussion.
in the klipper folder you can find a firmware builder image. It is unfortunately not documented yet.
https://github.com/dimalo/klipper-web-control-docker/blob/main/klipper/builder.Dockerfile

Basically you can build the builder image with `docker build --pull --rm -f "klipper/builder.Dockerfile" -t  klipper-builder:latest "klipper"` and then run a container with `docker run --rm -it -v $PWD/klipper_firmware:/home/klippy/klipper/out  klipper-builder:latest`
It will start a bash terminal you can then `make menuconfig`and `make` and leave the container
afterwards get your binary in local folder called klipper_firmware

**Comment by Andoramb** [comment]
Thanks @dimalo!
Do you have any idea why is it complaining for systemctl?
_No such file or directory: 'systemctl'_

**Comment by dimalo** [comment]
Systemd is not installed and not supported in containers. Didn't complain for me...
Are you trying to flash/install from the builder?

**Comment by Andoramb** [comment]
sorry @dimalo for the late reply (been very busy with the kid around the house)
I still get the same error, tried to fault trace it, restart fresh according to the descriptions, but at this point I give up :)
Timewise it's easier to just go with a pi :)
Too bad for me, but I've learnt a lot! 
Thanks for your work :)
